local_backend: true

backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/project.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Blurb", name: "blurb", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "string"}
